### ISSUE TITLE
Make models and data available on the Hugging Face Hub

### ISSUE THREAD

**Issue by davanstrien** [frankkramer-lab/GPTNERMED#1]
Very nice project! It would be great to make the models and data available on the Hugging Face Hub too. Feel free to ping me if you are interested and want any help with that :)

**Comment by j-frei** [comment]
Hey @davanstrien 
Thank you for your feedback!
I finally added the models and dataset to the HuggingFace Hub. (See README) :)

Regarding the dataset hub, I am still unsure whether I correctly implemented the dataset loader script. :pray: 
https://huggingface.co/datasets/jfrei/GPTNERMED/blob/main/GPTNERMED.py

I guess providing a set of dataset loader scripts for different tasks and formats might be highly beneficial to a lot of people in the future. Other than that, the dataset import process works fantastic! :+1: 

Thank you for your support and feel free to tell me whether the dataloader script seems fine. :smiley: 

Cheers,
Johann
